server:
  port: 80

spring:
  datasource:                                           # 数据源的相关配置
    url: jdbc:mysql://localhost:3306/laba-foodie?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: 123456
    username: root