server:
  port: 4000

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mall_pms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: xinfago
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  application:
    name: mall-product

# 配置mybatis-plus逻辑删除
mybatis-plus:
  global-config:
    db-config:
#      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml

logging:
  level:
    com.xinfago.mall: debug